"""Execute AI decision and send orders immediately (one-shot).

This script imports helpers from tools.live_run_controller and runs them.
It requires that `control/apply_live.confirm` and `control/apply_live.auto.confirm`
exist and that ALLOW_MT5_SEND=1 is set in the environment to perform real sends.
"""
import os
import pprint

from tools.live_run_controller import ai_decide_orders, send_orders_via_mt5, has_auto_confirmation


def main():
    symbols_env = os.getenv('SYMBOLS')
    if symbols_env:
        symbols = [s.strip() for s in symbols_env.split(',') if s.strip()]
    else:
        symbols = [
            "BTCUSD", "ETHUSD", "XAUUSD", "USDCAD", "AUDNZD", "EURJPY",
            "GBPCHF", "NZDJPY", "EURUSD", "EURAUD", "US500.cash", "JP225.cash",
        ]

    volume = float(os.getenv('AI_VOLUME', '0.01'))

    print('AI: deciding orders for symbols:', symbols)
    orders = ai_decide_orders(symbols, volume=volume)
    if not orders:
        print('No orders generated by AI - aborting')
        return

    print('\n=== Orders preview ===')
    pprint.pprint(orders)

    # Check auto-confirmation and ALLOW_MT5_SEND
    allow = os.getenv('ALLOW_MT5_SEND') == '1'
    auto_conf = has_auto_confirmation()
    print('\nAuto-confirm present:', auto_conf, 'ALLOW_MT5_SEND=1?', allow)

    if not (auto_conf and allow):
        print('Not sending: missing auto-confirmation or ALLOW_MT5_SEND!=1')
        return

    print('\nSending orders now...')
    results = send_orders_via_mt5(orders)
    print('\n=== Send results ===')
    for o, r in results:
        print('Order for', o['symbol'], 'result:', r)


if __name__ == '__main__':
    main()
